### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [solomobro/Instagram#6]
Hey man, can you apply this to your project?

ability to get all the people you following and checks if they following you back if they not it will unfollow them.

**Comment by dialalpha** [comment]
@di48l069: Thanks for the suggestion. Unfortunately, this feature is a business rule, and therefore is beyond the scope of this project. All we intend to do here is wrap the Instagram API. Users would need to implement their own logic around the SDK.

**Comment by ghost** [comment]
@dialalpha no problemo
